# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastro_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cadastro3(object):
    def setupUi(self, Cadastro3):
        Cadastro3.setObjectName("Cadastro3")
        Cadastro3.resize(542, 434)
        self.centralwidget = QtWidgets.QWidget(Cadastro3)
        self.centralwidget.setStyleSheet("background-color: rgb(76, 76, 76);")
        self.centralwidget.setObjectName("centralwidget")
        self.background_gym = QtWidgets.QLabel(self.centralwidget)
        self.background_gym.setGeometry(QtCore.QRect(10, 0, 531, 431))
        self.background_gym.setText("")
        self.background_gym.setObjectName("background_gym")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 10, 251, 51))
        self.label.setStyleSheet("font: 20pt \"Bahnschrift SemiLight Condensed\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 191, 31))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Bahnschrift SemiLight Condensed\";")
        self.label_2.setObjectName("label_2")
        self.input_NomeCompleto = QtWidgets.QLineEdit(self.centralwidget)
        self.input_NomeCompleto.setGeometry(QtCore.QRect(20, 100, 191, 21))
        self.input_NomeCompleto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_NomeCompleto.setObjectName("input_NomeCompleto")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 191, 31))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Bahnschrift SemiLight Condensed\";")
        self.label_3.setObjectName("label_3")
        self.input_DataNasc = QtWidgets.QDateEdit(self.centralwidget)
        self.input_DataNasc.setGeometry(QtCore.QRect(20, 180, 110, 22))
        self.input_DataNasc.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_DataNasc.setObjectName("input_DataNasc")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 70, 191, 31))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Bahnschrift SemiLight Condensed\";")
        self.label_4.setObjectName("label_4")
        self.input_endereco = QtWidgets.QLineEdit(self.centralwidget)
        self.input_endereco.setGeometry(QtCore.QRect(310, 100, 211, 20))
        self.input_endereco.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_endereco.setObjectName("input_endereco")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(310, 150, 191, 31))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Bahnschrift SemiLight Condensed\";")
        self.label_5.setObjectName("label_5")
        self.input_Telefone = QtWidgets.QLineEdit(self.centralwidget)
        self.input_Telefone.setGeometry(QtCore.QRect(310, 180, 161, 20))
        self.input_Telefone.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_Telefone.setObjectName("input_Telefone")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 220, 191, 31))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Bahnschrift SemiLight Condensed\";")
        self.label_6.setObjectName("label_6")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 210, 511, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 130, 511, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.inputbox_Planos = QtWidgets.QComboBox(self.centralwidget)
        self.inputbox_Planos.setGeometry(QtCore.QRect(20, 250, 201, 22))
        self.inputbox_Planos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inputbox_Planos.setEditable(False)
        self.inputbox_Planos.setObjectName("inputbox_Planos")
        self.inputbox_Planos.addItem("")
        self.inputbox_Planos.addItem("")
        self.inputbox_Planos.addItem("")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(310, 220, 191, 31))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Bahnschrift SemiLight Condensed\";")
        self.label_7.setObjectName("label_7")
        self.input_DataInicio = QtWidgets.QDateEdit(self.centralwidget)
        self.input_DataInicio.setGeometry(QtCore.QRect(310, 250, 131, 22))
        self.input_DataInicio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_DataInicio.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.input_DataInicio.setCalendarPopup(True)
        self.input_DataInicio.setObjectName("input_DataInicio")
        self.button_cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.button_cadastrar.setGeometry(QtCore.QRect(160, 300, 171, 61))
        self.button_cadastrar.setStyleSheet("font: 14pt \"Bahnschrift SemiLight Condensed\";\n"
"background-color: rgb(85, 255, 127);")
        self.button_cadastrar.setObjectName("button_cadastrar")
        self.label_Erros = QtWidgets.QLabel(self.centralwidget)
        self.label_Erros.setGeometry(QtCore.QRect(70, 380, 381, 31))
        self.label_Erros.setStyleSheet("font: 14pt \"Bahnschrift SemiLight Condensed\";")
        self.label_Erros.setText("")
        self.label_Erros.setObjectName("label_Erros")
        Cadastro3.setCentralWidget(self.centralwidget)

        self.retranslateUi(Cadastro3)
        QtCore.QMetaObject.connectSlotsByName(Cadastro3)

    def retranslateUi(self, Cadastro3):
        _translate = QtCore.QCoreApplication.translate
        Cadastro3.setWindowTitle(_translate("Cadastro3", "CADASTRO ALUNO(A)"))
        self.label.setText(_translate("Cadastro3", "CADASTRO NOVOS ALUNOS"))
        self.label_2.setText(_translate("Cadastro3", "NOME COMPLETO ALUNO(A):"))
        self.label_3.setText(_translate("Cadastro3", "DATA DE NASCIMENTO:"))
        self.label_4.setText(_translate("Cadastro3", "ENDEREÇO:"))
        self.label_5.setText(_translate("Cadastro3", "TELEFONE:"))
        self.label_6.setText(_translate("Cadastro3", "TIPO DE PLANO:"))
        self.inputbox_Planos.setCurrentText(_translate("Cadastro3", "Plano Mensal R$125,00  (30 dias)"))
        self.inputbox_Planos.setItemText(0, _translate("Cadastro3", "Plano Mensal R$125,00  (30 dias)"))
        self.inputbox_Planos.setItemText(1, _translate("Cadastro3", "Plano Trimensal R$100,00 (90 dias)"))
        self.inputbox_Planos.setItemText(2, _translate("Cadastro3", "Plano Anual R$75,00 (365 dias)"))
        self.label_7.setText(_translate("Cadastro3", "INICIO DAS ATIVIDADES:"))
        self.button_cadastrar.setText(_translate("Cadastro3", "CADASTRAR!"))
