# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_listagem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JanelaListagem(object):
    def setupUi(self, JanelaListagem):
        JanelaListagem.setObjectName("JanelaListagem")
        JanelaListagem.resize(1147, 717)
        JanelaListagem.setStyleSheet("background-color: rgb(59, 59, 59);")
        self.centralwidget = QtWidgets.QWidget(JanelaListagem)
        self.centralwidget.setObjectName("centralwidget")
        self.button_ShowAll = QtWidgets.QPushButton(self.centralwidget)
        self.button_ShowAll.setGeometry(QtCore.QRect(10, 580, 191, 61))
        self.button_ShowAll.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 14pt \"Bahnschrift SemiLight Condensed\";")
        self.button_ShowAll.setObjectName("button_ShowAll")
        self.lista_de_alunos = QtWidgets.QListWidget(self.centralwidget)
        self.lista_de_alunos.setGeometry(QtCore.QRect(10, 10, 1121, 551))
        self.lista_de_alunos.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 11pt \"Bahnschrift SemiLight Condensed\";")
        self.lista_de_alunos.setObjectName("lista_de_alunos")
        self.input_NomePesquisa = QtWidgets.QLineEdit(self.centralwidget)
        self.input_NomePesquisa.setGeometry(QtCore.QRect(220, 580, 181, 21))
        self.input_NomePesquisa.setObjectName("input_NomePesquisa")
        self.button_pesquisaNome = QtWidgets.QPushButton(self.centralwidget)
        self.button_pesquisaNome.setGeometry(QtCore.QRect(220, 610, 181, 31))
        self.button_pesquisaNome.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"font: 14pt \"Bahnschrift SemiLight Condensed\";")
        self.button_pesquisaNome.setObjectName("button_pesquisaNome")
        self.button_PesquisaNumero = QtWidgets.QPushButton(self.centralwidget)
        self.button_PesquisaNumero.setGeometry(QtCore.QRect(430, 610, 211, 31))
        self.button_PesquisaNumero.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"font: 12pt \"Bahnschrift SemiLight Condensed\";")
        self.button_PesquisaNumero.setObjectName("button_PesquisaNumero")
        self.input_NumeroTelefonepesquisa = QtWidgets.QLineEdit(self.centralwidget)
        self.input_NumeroTelefonepesquisa.setGeometry(QtCore.QRect(430, 580, 211, 20))
        self.input_NumeroTelefonepesquisa.setObjectName("input_NumeroTelefonepesquisa")
        self.label_Erros = QtWidgets.QLabel(self.centralwidget)
        self.label_Erros.setGeometry(QtCore.QRect(310, 680, 471, 21))
        self.label_Erros.setStyleSheet("font: 14pt \"Bahnschrift SemiLight Condensed\";\n"
"color: rgb(255, 170, 0);")
        self.label_Erros.setText("")
        self.label_Erros.setObjectName("label_Erros")
        self.button_Vencimentos = QtWidgets.QPushButton(self.centralwidget)
        self.button_Vencimentos.setGeometry(QtCore.QRect(680, 580, 191, 61))
        self.button_Vencimentos.setStyleSheet("background-color: rgb(188, 0, 0);\n"
"font: 12pt \"Bahnschrift SemiLight Condensed\";")
        self.button_Vencimentos.setObjectName("button_Vencimentos")
        self.button_AdicionarPlano = QtWidgets.QPushButton(self.centralwidget)
        self.button_AdicionarPlano.setGeometry(QtCore.QRect(900, 580, 191, 61))
        self.button_AdicionarPlano.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_AdicionarPlano.setStyleSheet("background-color: rgb(85, 255, 0);\n"
"font: 14pt \"Bahnschrift SemiLight Condensed\";\n"
"background-color: rgb(85, 255, 127);")
        self.button_AdicionarPlano.setObjectName("button_AdicionarPlano")
        JanelaListagem.setCentralWidget(self.centralwidget)

        self.retranslateUi(JanelaListagem)
        QtCore.QMetaObject.connectSlotsByName(JanelaListagem)

    def retranslateUi(self, JanelaListagem):
        _translate = QtCore.QCoreApplication.translate
        JanelaListagem.setWindowTitle(_translate("JanelaListagem", "CONSULTA ALUNO(A)s"))
        self.button_ShowAll.setText(_translate("JanelaListagem", "MOSTRAR TODOS ALUNOS!"))
        self.button_pesquisaNome.setText(_translate("JanelaListagem", "PESQUISAR POR NOME"))
        self.button_PesquisaNumero.setText(_translate("JanelaListagem", "PESQUISAR POR NUMERO DE TELEFONE"))
        self.button_Vencimentos.setText(_translate("JanelaListagem", "EM FIM DE CONTRATO/vencimento"))
        self.button_AdicionarPlano.setText(_translate("JanelaListagem", "EDITAR/ADICIONAR PLANO"))
