# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela1_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Janela1(object):
    def setupUi(self, Janela1):
        Janela1.setObjectName("Janela1")
        Janela1.resize(634, 468)
        Janela1.setFocusPolicy(QtCore.Qt.ClickFocus)
        Janela1.setAcceptDrops(True)
        Janela1.setStyleSheet("background-color: rgb(255, 255, 255);")
        Janela1.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget = QtWidgets.QWidget(Janela1)
        self.centralwidget.setObjectName("centralwidget")
        self.input_usuario = QtWidgets.QLineEdit(self.centralwidget)
        self.input_usuario.setGeometry(QtCore.QRect(230, 230, 161, 21))
        self.input_usuario.setStyleSheet("background-color: rgb(184, 184, 184);")
        self.input_usuario.setText("")
        self.input_usuario.setObjectName("input_usuario")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 190, 171, 31))
        self.label.setStyleSheet("font: 16pt \"Bahnschrift SemiLight Condensed\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 270, 161, 31))
        self.label_2.setStyleSheet("font: 16pt \"Bahnschrift SemiLight Condensed\";")
        self.label_2.setObjectName("label_2")
        self.button_login = QtWidgets.QPushButton(self.centralwidget)
        self.button_login.setGeometry(QtCore.QRect(250, 340, 111, 41))
        self.button_login.setStyleSheet("font: 16pt \"Bahnschrift SemiLight Condensed\";")
        self.button_login.setObjectName("button_login")
        self.input_Senha = QtWidgets.QLineEdit(self.centralwidget)
        self.input_Senha.setGeometry(QtCore.QRect(230, 310, 161, 20))
        self.input_Senha.setStyleSheet("background-color: rgb(181, 181, 181);")
        self.input_Senha.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.input_Senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_Senha.setObjectName("input_Senha")
        self.label_Error = QtWidgets.QLabel(self.centralwidget)
        self.label_Error.setGeometry(QtCore.QRect(120, 410, 391, 41))
        self.label_Error.setStyleSheet("font: 16pt \"Bahnschrift SemiLight Condensed\";")
        self.label_Error.setText("")
        self.label_Error.setObjectName("label_Error")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(50, 20, 541, 151))
        self.label_logo.setText("")
        self.label_logo.setObjectName("label_logo")
        Janela1.setCentralWidget(self.centralwidget)

        self.retranslateUi(Janela1)
        QtCore.QMetaObject.connectSlotsByName(Janela1)

    def retranslateUi(self, Janela1):
        _translate = QtCore.QCoreApplication.translate
        Janela1.setWindowTitle(_translate("Janela1", "LOGIN ACADEMIA"))
        self.label.setText(_translate("Janela1", "LOGIN ADMINISTRADOR:"))
        self.label_2.setText(_translate("Janela1", "SENHA ADMINISTRADOR:"))
        self.button_login.setText(_translate("Janela1", "LOGIN"))
